levels:
  md:
    discovery:
      markdown:
    tool:
      markdownlint:
        flags: ""

  md_with_pylint:
    inherits_from: "md"
    discovery:
      python:
    tool:
      pylint:
        flags: "--good-names=f,i,j,k,x,y,z,ex,_"
